### ISSUE TITLE
1.2.2.a seems incorrect

### ISSUE THREAD

**Issue by nemmons** [mikinty/Understanding-Analysis-Abbott-Solutions#6]
The problem clams that `A_n` is a subset of `A_n+1` and so on; I don't believe that would hold for your example of `A_n = [0, 1/n)`, as the size of the set would decrease as n goes to infinity. 

I believe that since we know that `A_1` is infinite and also a subset of `A_n` for all n > 1, the intersection of all such sets would equal `A_1` which is infinite, so this is True. 

If you agree with this reasoning, i can attempt a PR to adjust the solution. (Apologies if I'm making a stupid mistake here - I'm coming back to math after a decade out of college)

**Comment by nemmons** [comment]
Also, thanks for all your work in writing all these solutions up and sharing them. I'm sure it will be incredibly helpful to me as I work through this text via self-study!

**Comment by mikinty** [comment]
No I think you have mistaken the `\subseteq` (subset) and `\supseteq` (superset) notations. In the textbook, the problem is saying that 

```
A_1 \supseteq A_2 \supseteq A_3 \cdots
```

Meaning `A_1` is a superset of `A_2`, or `A_2` is a subset of `A_1`, which is true for the example I've given.

I do agree that if we had `A_j subseteq A_k, k \geq j` instead, the statement would be true.

Good luck with your studies!

**Comment by nemmons** [comment]
Oh wow. that's embarrassing. Thanks for the clarification!
