### ISSUE TITLE
Answer to 2.3.2 is just wrong.

### ISSUE THREAD

**Issue by zhizhongpu** [mikinty/Understanding-Analysis-Abbott-Solutions#7]
The correct proof follows 2nd edition p.52 (iv.)

**Comment by mikinty** [comment]
Do you want to take care of this? Otherwise I can probably fix this sometime...haven't studied analysis in a while lol

**Comment by zhizhongpu** [comment]
Sure. I can fork this when I've got time.

**Comment by mikinty** [comment]
Why is this answer wrong? I think it should be mentioned that these solutions are for the first edition I believe, not the second edition. There is a fork that is for the second edition.

I'm rewording the solution so it's more of a delta-epsilon style (I think a friend wrote the original solution), but I don't think this proof is egregiously wrong.

In the future if you want to point out a solution is wrong, can you please indicate what the error is? "Just wrong" is not very helpful.

**Comment by mikinty** [comment]
#8 resolved here

**Comment by peacefulzephyr** [comment]
To clarify, it's not an edition issue; the prompt is correct and accurate.
Please see attached for the error (which is why the original method would not work). I am happy to explain further if you need additional pin-point. Hope it helps. 
![image](https://user-images.githubusercontent.com/84325421/158080452-87135bed-db0b-47e5-b5eb-8bc8635d1c50.png)

**Comment by zhizhongpu** [comment]
Thanks for the clarification!

**Comment by mikinty** [comment]
I'm not sure where you got your screenshot for 2.3.2, but my textbook didn't have those.

For reference these were the solutions, which I'm pretty sure originally were not wrong themselves.

![image](https://user-images.githubusercontent.com/12106484/158082074-a8eec78b-6d81-4584-b81b-f331f527d6a0.png)

**Comment by mikinty** [comment]
To solve your 2.3.2b), you should say that because $(x_n) \to 2$, we can choose some $N$ such that $\abs(x_n - 2) < \epsilon_1$. Now, if we consider $\frac{1}{2x_n}$, this will be $\leq \frac{1}{2(x_n - \epsilon_1)}$, let's call this RHS $A$.

Now, we have $\abs{x_n - 2}$, which we know we can make as small as possible, times $A$. The $N_2$ we have to choose to prove our bound is such that $\abs{x_n - 2} < \epsilon \cdot \frac{1}{A}$, and finally, since we don't know which $N$ is bigger, we take $\max(N, N_2}$.

Something like that...

I do agree the 1/M bound is not correct since inequalities flip when we flip fractions. 

Problem in question: 
![image](https://user-images.githubusercontent.com/12106484/158082431-c507b09e-25a9-4030-9888-00cf4ef2336d.png)
